/*
 * Vectorizer.AI API
 *
 * OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vectorizer.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vectorizer.AI.Client.OpenAPIDateConverter;

namespace Vectorizer.AI.Model
{
    /// <summary>
    /// AccountStatusResponse
    /// </summary>
    [DataContract(Name = "AccountStatusResponse")]
    public partial class AccountStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountStatusResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountStatusResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountStatusResponse" /> class.
        /// </summary>
        /// <param name="subscriptionPlan">The subscription plan currently associated with the account, or &#39;none&#39;. (required).</param>
        /// <param name="subscriptionState">The current subscription state: &#39;active&#39;, &#39;pastDue&#39;, or &#39;ended&#39;. (required).</param>
        /// <param name="credits">The number of API credits left. Can be fractional, so parse as a double-precision number. (required).</param>
        public AccountStatusResponse(string subscriptionPlan = default(string), string subscriptionState = default(string), double credits = default(double))
        {
            // to ensure "subscriptionPlan" is required (not null)
            if (subscriptionPlan == null)
            {
                throw new ArgumentNullException("subscriptionPlan is a required property for AccountStatusResponse and cannot be null");
            }
            this.SubscriptionPlan = subscriptionPlan;
            // to ensure "subscriptionState" is required (not null)
            if (subscriptionState == null)
            {
                throw new ArgumentNullException("subscriptionState is a required property for AccountStatusResponse and cannot be null");
            }
            this.SubscriptionState = subscriptionState;
            this.Credits = credits;
        }

        /// <summary>
        /// The subscription plan currently associated with the account, or &#39;none&#39;.
        /// </summary>
        /// <value>The subscription plan currently associated with the account, or &#39;none&#39;.</value>
        [DataMember(Name = "subscriptionPlan", IsRequired = true, EmitDefaultValue = true)]
        public string SubscriptionPlan { get; set; }

        /// <summary>
        /// The current subscription state: &#39;active&#39;, &#39;pastDue&#39;, or &#39;ended&#39;.
        /// </summary>
        /// <value>The current subscription state: &#39;active&#39;, &#39;pastDue&#39;, or &#39;ended&#39;.</value>
        [DataMember(Name = "subscriptionState", IsRequired = true, EmitDefaultValue = true)]
        public string SubscriptionState { get; set; }

        /// <summary>
        /// The number of API credits left. Can be fractional, so parse as a double-precision number.
        /// </summary>
        /// <value>The number of API credits left. Can be fractional, so parse as a double-precision number.</value>
        [DataMember(Name = "credits", IsRequired = true, EmitDefaultValue = true)]
        public double Credits { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountStatusResponse {\n");
            sb.Append("  SubscriptionPlan: ").Append(SubscriptionPlan).Append("\n");
            sb.Append("  SubscriptionState: ").Append(SubscriptionState).Append("\n");
            sb.Append("  Credits: ").Append(Credits).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
