/*
 * Vectorizer.AI API
 *
 * OpenAPI 3.0 specification for the Vectorizer.AI image vectorization API. Authenticate with HTTP Basic auth, using your API Id as the username and your API Secret as the password.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@vectorizer.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Vectorizer.AI.Client.OpenAPIDateConverter;

namespace Vectorizer.AI.Model
{
    /// <summary>
    /// ErrorResponse
    /// </summary>
    [DataContract(Name = "ErrorResponse")]
    public partial class ErrorResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ErrorResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorResponse" /> class.
        /// </summary>
        /// <param name="error">error (required).</param>
        /// <param name="dataReceived">Echo of the submitted request data when available. File uploads are summarized instead of echoed. (required).</param>
        public ErrorResponse(ErrorResponseError error = default(ErrorResponseError), Dictionary<string, Object> dataReceived = default(Dictionary<string, Object>))
        {
            // to ensure "error" is required (not null)
            if (error == null)
            {
                throw new ArgumentNullException("error is a required property for ErrorResponse and cannot be null");
            }
            this.Error = error;
            // to ensure "dataReceived" is required (not null)
            if (dataReceived == null)
            {
                throw new ArgumentNullException("dataReceived is a required property for ErrorResponse and cannot be null");
            }
            this.DataReceived = dataReceived;
        }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", IsRequired = true, EmitDefaultValue = true)]
        public ErrorResponseError Error { get; set; }

        /// <summary>
        /// Echo of the submitted request data when available. File uploads are summarized instead of echoed.
        /// </summary>
        /// <value>Echo of the submitted request data when available. File uploads are summarized instead of echoed.</value>
        [DataMember(Name = "dataReceived", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, Object> DataReceived { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorResponse {\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  DataReceived: ").Append(DataReceived).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
